#!/usr/bin/env node
/**
 * safari-version.mjs — the Mac app's CFBundleShortVersionString / CFBundleVersion,
 * derived from apps/extension/package.json so the Safari wrapper can never drift
 * from the extension it embeds (App Store Connect also requires the appex and its
 * host app to carry identical values — both targets read the same xcconfig).
 *
 *   MARKETING_VERSION       = package.json `version` (semver, e.g. 0.1.2)
 *   CURRENT_PROJECT_VERSION = major·1 000 000 + minor·10 000 + patch·100 + suffix
 *                             (0.1.2 → 10200; monotonic across versions; the
 *                             two-digit `suffix` — env SAFARI_BUILD_SUFFIX, default
 *                             0 — is for re-uploading the SAME version, which App
 *                             Store Connect only accepts with a higher build number)
 *
 *   node scripts/safari-version.mjs           # print {version, build}
 *   node scripts/safari-version.mjs --write   # (re)write safari-app/Version.xcconfig
 *   node scripts/safari-version.mjs --check   # exit 1 if the committed xcconfig is stale
 *
 * Pure helpers are exported for safari-version.test.ts.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const EXT_DIR = join(dirname(fileURLToPath(import.meta.url)), "..");
export const XCCONFIG_PATH = join(EXT_DIR, "safari-app", "Version.xcconfig");

/** Strict `major.minor.patch` (no pre-release/build metadata — Apple rejects them). */
export function parseVersion(version) {
  const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(String(version).trim());
  if (!m) throw new Error(`safari-version: "${version}" is not a plain major.minor.patch version`);
  const [major, minor, patch] = m.slice(1).map(Number);
  if (minor > 99 || patch > 99) {
    throw new Error(`safari-version: minor/patch must be ≤ 99 to keep CFBundleVersion monotonic (got ${version})`);
  }
  return { major, minor, patch };
}

/** Numeric CFBundleVersion — see the file header for the encoding. */
export function deriveBuildNumber(version, suffix = 0) {
  const s = Number(suffix);
  if (!Number.isInteger(s) || s < 0 || s > 99) {
    throw new Error(`safari-version: build suffix must be an integer 0–99 (got ${suffix})`);
  }
  const { major, minor, patch } = parseVersion(version);
  return major * 1_000_000 + minor * 10_000 + patch * 100 + s;
}

export function renderXcconfig(version, build) {
  return [
    "// GENERATED by apps/extension/scripts/safari-version.mjs from apps/extension/package.json — do not edit.",
    "// MARKETING_VERSION = the extension version; CURRENT_PROJECT_VERSION = major*1000000 + minor*10000 + patch*100 + SAFARI_BUILD_SUFFIX.",
    `MARKETING_VERSION = ${version}`,
    `CURRENT_PROJECT_VERSION = ${build}`,
    "",
  ].join("\n");
}

/** Parse the two settings back out of an xcconfig body. */
export function parseXcconfig(text) {
  const get = (key) => {
    const m = new RegExp(`^${key}\\s*=\\s*(\\S+)\\s*$`, "m").exec(text);
    return m ? m[1] : undefined;
  };
  return { version: get("MARKETING_VERSION"), build: Number(get("CURRENT_PROJECT_VERSION")) };
}

export function currentValues(env = process.env) {
  const pkg = JSON.parse(readFileSync(join(EXT_DIR, "package.json"), "utf8"));
  const version = pkg.version;
  const build = deriveBuildNumber(version, env.SAFARI_BUILD_SUFFIX ?? 0);
  return { version, build };
}

function main(argv) {
  const { version, build } = currentValues();
  if (argv.includes("--write")) {
    writeFileSync(XCCONFIG_PATH, renderXcconfig(version, build));
    console.log(`[safari-version] wrote ${XCCONFIG_PATH}: MARKETING_VERSION=${version} CURRENT_PROJECT_VERSION=${build}`);
    return;
  }
  if (argv.includes("--check")) {
    const onDisk = parseXcconfig(readFileSync(XCCONFIG_PATH, "utf8"));
    if (onDisk.version !== version || onDisk.build !== build) {
      console.error(
        `[safari-version] safari-app/Version.xcconfig is stale: has ${onDisk.version} (${onDisk.build}), ` +
          `package.json says ${version} (${build}). Run: node scripts/safari-version.mjs --write`,
      );
      process.exit(1);
    }
    console.log(`[safari-version] Version.xcconfig in sync: ${version} (${build})`);
    return;
  }
  console.log(JSON.stringify({ version, build }));
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2));
}
