#!/usr/bin/env bash
#
# sync-safari-native.sh — patch the (gitignored, converter-generated) Safari wrapper app
# with our COMMITTED native sources + settings so it becomes a menu-bar background app.
#
# Why this exists: `safari-xcode/` is regenerated by `xcrun safari-web-extension-converter`
# and is .gitignored, so anything we change inside it is lost on the next reconversion. The
# real sources live in `apps/extension/safari-native/` (committed); this script stamps them
# back onto the generated project. Run it after every reconversion, before `xcodebuild`.
#
# It is idempotent and safe to re-run. It:
#   (a) copies AppDelegate.swift + ViewController.swift over the generated ones,
#   (b) fixes the app target's bundle id (ai.bookmark.Bookmark-AI -> ai.bookmark.safari) if
#       the converter still mis-namespaces it,
#   (c) sets LSUIElement=true in the APP's Info.plist (no Dock icon — menu-bar only),
#   (d) prints the signed xcodebuild command to run next.
#
set -euo pipefail

# --- Resolve repo paths from any cwd --------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"                      # apps/extension
NATIVE_DIR="$EXT_DIR/safari-native"                          # committed sources
APP_PROJECT_DIR="$EXT_DIR/safari-xcode/Bookmark AI"          # generated .xcodeproj lives here
APP_SRC_DIR="$APP_PROJECT_DIR/Bookmark AI"                   # generated app target sources
PBXPROJ="$APP_PROJECT_DIR/Bookmark AI.xcodeproj/project.pbxproj"
APP_INFO_PLIST="$APP_SRC_DIR/Info.plist"

CONVERTER_CMD='cd apps/extension && xcrun safari-web-extension-converter .output/safari-mv2 --app-name "Bookmark AI" --bundle-identifier ai.bookmark.safari --project-location safari-xcode --macos-only --no-open --no-prompt --force'

# --- Guard: generated project must exist ----------------------------------------------
if [[ ! -d "$APP_SRC_DIR" || ! -f "$PBXPROJ" ]]; then
  echo "ERROR: generated Safari project not found at:" >&2
  echo "  $APP_PROJECT_DIR" >&2
  echo >&2
  echo "safari-xcode/ is gitignored and must be regenerated with the converter first:" >&2
  echo >&2
  echo "  $CONVERTER_CMD" >&2
  echo >&2
  echo "(from the repo root). Then re-run this script." >&2
  exit 1
fi

# --- (a) Copy committed Swift sources over the generated ones -------------------------
for f in AppDelegate.swift ViewController.swift; do
  if [[ ! -f "$NATIVE_DIR/$f" ]]; then
    echo "ERROR: missing committed source $NATIVE_DIR/$f" >&2
    exit 1
  fi
  cp "$NATIVE_DIR/$f" "$APP_SRC_DIR/$f"
  echo "synced  $f -> Bookmark AI/Bookmark AI/$f"
done

# --- (b) Fix app-target bundle id if the converter still mis-namespaces it -------------
if grep -q 'PRODUCT_BUNDLE_IDENTIFIER = "ai.bookmark.Bookmark-AI";' "$PBXPROJ"; then
  sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = "ai.bookmark.Bookmark-AI";/PRODUCT_BUNDLE_IDENTIFIER = ai.bookmark.safari;/g' "$PBXPROJ"
  echo "patched bundle id -> ai.bookmark.safari"
else
  echo "bundle id already ai.bookmark.safari (no-op)"
fi

# --- (c) LSUIElement=true in the APP's Info.plist (no Dock icon) -----------------------
PLIST_BUDDY=/usr/libexec/PlistBuddy
if "$PLIST_BUDDY" -c "Print :LSUIElement" "$APP_INFO_PLIST" >/dev/null 2>&1; then
  "$PLIST_BUDDY" -c "Set :LSUIElement true" "$APP_INFO_PLIST"
  echo "set LSUIElement=true (already present)"
else
  "$PLIST_BUDDY" -c "Add :LSUIElement bool true" "$APP_INFO_PLIST"
  echo "added LSUIElement=true"
fi

# --- (d) Remind of the signed build command -------------------------------------------
cat <<EOF

Done. Now build (signed) from the project dir:

  cd "apps/extension/safari-xcode/Bookmark AI"
  xcodebuild -project "Bookmark AI.xcodeproj" -scheme "Bookmark AI" -configuration Debug clean build CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="Apple Development: tarachandragupta2784@gmail.com (BB7CP2R7GG)" DEVELOPMENT_TEAM=L3PP7DQZWS PROVISIONING_PROFILE_SPECIFIER=""

Expect: ** BUILD SUCCEEDED **
EOF
