//
//  AppDelegate.swift
//  Bookmark AI
//
//  ⚠️ COMMITTED SOURCE OF TRUTH — do not edit the copy under `safari-xcode/`.
//  `safari-xcode/` is generated by `xcrun safari-web-extension-converter` and is
//  GITIGNORED, so it gets blown away on every reconversion. This file is the real,
//  version-controlled source; `apps/extension/scripts/sync-safari-native.sh` copies
//  it OVER the converter-generated `Bookmark AI/Bookmark AI/AppDelegate.swift`.
//  Edit here, then run the sync script.
//
//  This turns the converter's throwaway wrapper app into a proper macOS menu-bar
//  (background/agent) app: an NSStatusItem lives in the menu bar, the app keeps
//  running when its window closes, and it can register itself as a login item so it
//  starts silently at login (menu-bar icon only, no window, no Dock icon — the Dock
//  icon is suppressed via LSUIElement, set by the sync script).
//

import Cocoa
import SafariServices
import ServiceManagement

@main
class AppDelegate: NSObject, NSApplicationDelegate, NSMenuDelegate {

    /// UserDefaults flag: have we ever finished a launch before? Drives the one-time
    /// onboarding window + "run in background?" prompt, and lets subsequent (login)
    /// launches stay silent.
    private let hasLaunchedBeforeKey = "ai.bookmark.safari.hasLaunchedBefore"

    private var statusItem: NSStatusItem!

    /// Menu items we mutate on `menuWillOpen` (live extension state + login-item check).
    private var extensionStateItem: NSMenuItem!
    private var loginItem: NSMenuItem!

    /// Retained so the onboarding window survives being closed (a menu-bar app must not
    /// die when its window closes) and can be re-shown on demand.
    private var windowController: NSWindowController?

    // MARK: - Lifecycle

    func applicationDidFinishLaunching(_ notification: Notification) {
        setUpStatusItem()

        let defaults = UserDefaults.standard
        let firstLaunch = !defaults.bool(forKey: hasLaunchedBeforeKey)

        if firstLaunch {
            defaults.set(true, forKey: hasLaunchedBeforeKey)
            // First run ever: behave like the original wrapper (show the setup window)…
            showSetupWindow()
            // …and, once, offer to run in the background at login. Deferred to the next
            // runloop tick so the window is on screen behind the alert.
            DispatchQueue.main.async { [weak self] in
                self?.presentBackgroundPrompt()
            }
        } else {
            // Subsequent launches (notably a login-item launch) must be silent: no window,
            // just the menu-bar icon. The storyboard auto-instantiates + shows its initial
            // window, so capture then close it. We keep the controller so "Show Setup
            // Window" / reopen can bring it back.
            _ = setupWindow()
            closeStoryboardWindows()
        }
    }

    /// A menu-bar app stays alive with no windows — closing the setup window must NOT quit.
    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        return false
    }

    /// Double-clicking the app in Finder (or `open`ing it again) re-shows the setup window.
    func applicationShouldHandleReopen(_ sender: NSApplication, hasVisibleWindows flag: Bool) -> Bool {
        showSetupWindow()
        return false
    }

    // MARK: - Status item / menu

    private func setUpStatusItem() {
        statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
        if let button = statusItem.button {
            let image = NSImage(systemSymbolName: "bookmark.fill", accessibilityDescription: "Bookmark AI")
            image?.isTemplate = true // template = adapts to light/dark menu bar automatically
            button.image = image
        }
        statusItem.menu = buildMenu()
    }

    private func buildMenu() -> NSMenu {
        let menu = NSMenu()
        menu.delegate = self // menuWillOpen refreshes the live rows each time it opens

        // Disabled status line — nil action + autoenable => greyed out. Text updated live.
        extensionStateItem = NSMenuItem(title: "Safari extension: unknown", action: nil, keyEquivalent: "")
        extensionStateItem.isEnabled = false
        menu.addItem(extensionStateItem)

        menu.addItem(.separator())

        menu.addItem(actionItem(title: "Open Safari Extension Settings…", selector: #selector(openExtensionSettings)))
        menu.addItem(actionItem(title: "Open Bookmark AI", selector: #selector(openWebApp)))
        menu.addItem(actionItem(title: "Show Setup Window", selector: #selector(showSetupWindowFromMenu)))

        menu.addItem(.separator())

        let login = actionItem(title: "Start at Login", selector: #selector(toggleLoginItem(_:)))
        if #available(macOS 13.0, *) {
            login.state = (SMAppService.mainApp.status == .enabled) ? .on : .off
        } else {
            // SMAppService is macOS 13+; hide the toggle entirely on older systems.
            login.isHidden = true
        }
        loginItem = login
        menu.addItem(login)

        menu.addItem(.separator())

        menu.addItem(actionItem(title: "Quit Bookmark AI", selector: #selector(quit), keyEquivalent: "q"))
        return menu
    }

    private func actionItem(title: String, selector: Selector, keyEquivalent: String = "") -> NSMenuItem {
        let item = NSMenuItem(title: title, action: selector, keyEquivalent: keyEquivalent)
        item.target = self
        return item
    }

    // MARK: - NSMenuDelegate

    func menuWillOpen(_ menu: NSMenu) {
        refreshExtensionStateItem()
        refreshLoginItemState()
    }

    /// `getStateOfSafariExtension` is async; the menu is already open, so updating the
    /// item's title when the callback lands re-renders it in place.
    private func refreshExtensionStateItem() {
        SFSafariExtensionManager.getStateOfSafariExtension(withIdentifier: extensionBundleIdentifier) { [weak self] state, error in
            let text: String
            if let state = state, error == nil {
                text = state.isEnabled ? "enabled" : "disabled"
            } else {
                text = "unknown"
            }
            DispatchQueue.main.async {
                self?.extensionStateItem.title = "Safari extension: \(text)"
            }
        }
    }

    private func refreshLoginItemState() {
        guard #available(macOS 13.0, *) else {
            loginItem?.isHidden = true
            return
        }
        loginItem?.state = (SMAppService.mainApp.status == .enabled) ? .on : .off
    }

    // MARK: - Menu actions

    @objc private func openExtensionSettings() {
        SFSafariApplication.showPreferencesForExtension(withIdentifier: extensionBundleIdentifier) { error in
            if let error = error {
                NSLog("Bookmark AI: showPreferencesForExtension failed: \(error)")
            }
        }
    }

    @objc private func openWebApp() {
        if let url = URL(string: "https://bookmark-ai.cloud/app") {
            NSWorkspace.shared.open(url)
        }
    }

    @objc private func showSetupWindowFromMenu() {
        showSetupWindow()
    }

    @objc private func quit() {
        NSApplication.shared.terminate(nil)
    }

    @objc private func toggleLoginItem(_ sender: NSMenuItem) {
        guard #available(macOS 13.0, *) else { return }
        do {
            if SMAppService.mainApp.status == .enabled {
                try SMAppService.mainApp.unregister()
            } else {
                try SMAppService.mainApp.register()
            }
        } catch {
            NSLog("Bookmark AI: login-item toggle failed: \(error)")
        }
        refreshLoginItemState()
    }

    // MARK: - Login item registration

    private func registerLoginItem() {
        guard #available(macOS 13.0, *) else { return }
        do {
            try SMAppService.mainApp.register()
        } catch {
            NSLog("Bookmark AI: SMAppService.register failed: \(error)")
        }
    }

    // MARK: - Onboarding window

    /// Lazily resolve (and retain) the storyboard's main window controller so the setup
    /// window can be shown/hidden repeatedly without being torn down.
    private func setupWindow() -> NSWindow? {
        if windowController == nil {
            if let existing = NSApp.windows.first(where: { $0.contentViewController is ViewController })?.windowController {
                windowController = existing
            } else {
                let storyboard = NSStoryboard(name: "Main", bundle: nil)
                windowController = storyboard.instantiateInitialController() as? NSWindowController
            }
        }
        // Never let closing the window deallocate it — we reuse it.
        windowController?.window?.isReleasedWhenClosed = false
        return windowController?.window
    }

    private func showSetupWindow() {
        guard let window = setupWindow() else { return }
        window.makeKeyAndOrderFront(nil)
        // LSUIElement apps are accessory apps; explicitly activate so the window comes forward.
        NSApp.activate(ignoringOtherApps: true)
    }

    private func closeStoryboardWindows() {
        for window in NSApp.windows where window.contentViewController is ViewController {
            window.close()
        }
    }

    private func presentBackgroundPrompt() {
        let alert = NSAlert()
        alert.messageText = "Run Bookmark AI in the background?"
        alert.informativeText = "Bookmark AI lives in your menu bar (the bookmark icon) and keeps its "
            + "Safari extension in sync while you browse. You can open this setup window again any "
            + "time from that menu.\n\nStart it automatically when you log in?"
        alert.addButton(withTitle: "Start at Login")
        alert.addButton(withTitle: "Not Now")
        if alert.runModal() == .alertFirstButtonReturn {
            registerLoginItem()
        }
    }
}
