//
//  ViewController.swift
//  Bookmark AI
//
//  ⚠️ COMMITTED SOURCE OF TRUTH — do not edit the copy under `safari-xcode/`.
//  `safari-xcode/` is generated by `xcrun safari-web-extension-converter` and is
//  GITIGNORED, so it is regenerated (and wiped) at will. This is the real,
//  version-controlled source; `apps/extension/scripts/sync-safari-native.sh` copies
//  it OVER the converter-generated `Bookmark AI/Bookmark AI/ViewController.swift`.
//
//  This is the converter's stock onboarding view controller with ONE behavioral
//  change: the "open-preferences" message no longer TERMINATES the app after opening
//  Safari's extension settings — it just closes the setup window. The app is now a
//  menu-bar background app (see AppDelegate.swift), so quitting on that click would be
//  wrong; the user stays running in the menu bar.
//

import Cocoa
import SafariServices
import WebKit

let extensionBundleIdentifier = "ai.bookmark.safari.Extension"

class ViewController: NSViewController, WKNavigationDelegate, WKScriptMessageHandler {

    @IBOutlet var webView: WKWebView!

    override func viewDidLoad() {
        super.viewDidLoad()

        self.webView.navigationDelegate = self

        self.webView.configuration.userContentController.add(self, name: "controller")

        self.webView.loadFileURL(Bundle.main.url(forResource: "Main", withExtension: "html")!, allowingReadAccessTo: Bundle.main.resourceURL!)
    }

    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        SFSafariExtensionManager.getStateOfSafariExtension(withIdentifier: extensionBundleIdentifier) { (state, error) in
            guard let state = state, error == nil else {
                // Insert code to inform the user that something went wrong.
                return
            }

            DispatchQueue.main.async {
                if #available(macOS 13, *) {
                    webView.evaluateJavaScript("show(\(state.isEnabled), true)")
                } else {
                    webView.evaluateJavaScript("show(\(state.isEnabled), false)")
                }
            }
        }
    }

    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
        if (message.body as! String != "open-preferences") {
            return;
        }

        SFSafariApplication.showPreferencesForExtension(withIdentifier: extensionBundleIdentifier) { error in
            DispatchQueue.main.async {
                // Menu-bar app: just dismiss the setup window instead of terminating —
                // the app keeps running in the menu bar (see AppDelegate.swift).
                self.view.window?.close()
            }
        }
    }

}
